### ISSUE TITLE
[Bug Report] 关注列表获取不全

### ISSUE THREAD

**Issue by FlipWind** [hmjz100/bilibili-comment-checker#1]
**问题描述**
关注列表获取不全。

**问题可能的原因**
当前 api 为 `https://api.bilibili.com/x/relation/followings?vmid=`, 但是注意到此参数的 api 获取的关注对象最多仅有 $50$ 个。

**可能的解决方案**
通过使用 `GET` 请求该接口，不难发现在接口返回内容的最后有一个 `total` 字段，猜测其对应为用户关注的数量。  
现在一种可能的解决方案是循环  $\lceil \frac{total}{50} \rceil$ 次以遍历整个关注列表，再使用 `map` 处理数据，以更全面地检测成分（

可以在接口后面加入 `pn=n` 参数以获取第 $n$ 页关注列表。

**Comment by hmjz100** [comment]
![1](https://github.com/user-attachments/assets/4dff34e7-440a-4226-b687-1a602e0ed2ff)

**Comment by FanxJK** [comment]
> ![1](https://private-user-images.githubusercontent.com/98228280/362569637-4dff34e7-440a-4226-b687-1a602e0ed2ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjEyMDUsIm5iZiI6MTcyNDkyMDkwNSwicGF0aCI6Ii85ODIyODI4MC8zNjI1Njk2MzctNGRmZjM0ZTctNDQwYS00MjI2LWI2ODctMWE2MDJlMGVkMmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA4NDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZWRhZGE1ODgzMGEyYzU2Zjc1ZWU5YmRkOTVlMTUxY2IyNmZiYzQ3YTJlYjc5MDYyNTBiMGM2M2ZlZTdmZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7zMbP3rfv7M0IpSz4URpAOzRtVYrrl6WPl67r5h93-Y)

前五页比只获取50个要准确

**Comment by rong-xiaoli** [comment]
插眼，同样的bug，自查貌似只能查到绝区零和抽奖，实际应该大于等于6个

**Comment by hmjz100** [comment]
感谢反馈，会尝试，下个版本发布，主要我怕请求多了 -352

**Comment by hmjz100** [comment]
刚测试了下，倒序似乎已经完全不起作用了，结果和正序的一样，新版本会只发布正序的

**Comment by hmjz100** [comment]
v2.0.0 已添加~
