### ISSUE TITLE
[Feature Request] 增加只显示关键词头像的选项、关闭 @ 标签成分显示选项

### ISSUE THREAD

**Issue by FlipWind** [hmjz100/bilibili-comment-checker#10]
**为什么：**
太多太杂了，不利于阅读。

**详细说明：**
1. 只显示关键词头像：
    - 目前的显示项有可能会在个人成分过多时而被挤出显示区域。因而，希望这里能够提供一个选项，使得成分项仅显示相关头像。
    - 例如，原来显示的是 [某头像，“成分”]，更改后变为 [某头像]，而不显示后面的文字。
2. 关闭 @ 标签成分显示选项：
    - 目前的评论区内若有人 @ 了其他人，则此时该标签后就会显示出被 @ 人的成分列表。虽然这是个不错的 feature，但是正如上面所说，这不利于阅读，且当被 @ 人太多后便会过于杂乱。所以请求是否能提供关闭 @ 标签后显示成分的可选项。

**Comment by hmjz100** [comment]
v2.0.1 已支持只显示关键词 Icon~  
不在 @ 显示成分这个比较有难度，目前暂无法关闭~
