### ISSUE TITLE
添加对夜间模式的支持

### ISSUE THREAD

**Issue by xinyihl** [hmjz100/bilibili-comment-checker#20]
我用的是 [Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved) 的夜间模式
现在的显示效果，那个 `无` 不应该是黑色的
![1](https://github.com/user-attachments/assets/24384843-adfb-4e78-bd57-2a4a7976df41)
![2](https://github.com/user-attachments/assets/a538820f-1d71-4fa2-a3a0-f84b49e0ae97)

**Comment by hmjz100** [comment]
这属于 [Bilibili Evolved](https://dgithub.xyz/the1812/Bilibili-Evolved) 夜间模式组件的 Bug，建议去那儿提issues  
一个可行的办法是关闭 [Bilibili Evolved](https://dgithub.xyz/the1812/Bilibili-Evolved) 的夜间模式，改为使用 Dark Reader 插件 + [Bilibili Evolved](https://dgithub.xyz/the1812/Bilibili-Evolved) 脚本  
替您测试过了 ，这么搭配没有任何问题

**Comment by hmjz100** [comment]
已按照您描述的问题进行修复~ 去安装 2.0.2 最新版就可以搭配 [Bilibili Evolved](https://dgithub.xyz/the1812/Bilibili-Evolved) 的夜间模式进行使用啦
