### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by SanXiQiong** [hmjz100/bilibili-comment-checker#21]
安装脚本之后，应该在哪查询呢，我安装了之后没啥变化，看别人的有的是在评论区用户名字后边有一个类似小方框的东西，

**Comment by SanXiQiong** [comment]
没问题了兄弟，是我没开开发者模式，现在解决了，哥们做的不错

**Comment by QiuLiang-99** [comment]
建议关闭此lssue
