### ISSUE TITLE
label:bug 重复出现成分标志

### ISSUE THREAD

**Issue by asoulist** [hmjz100/bilibili-comment-checker#22]
当同时使用此脚本和另一个类似功能的脚本[仙家军成分查询Helper](https://greasyfork.org/zh-CN/scripts/467197-%E4%BB%99%E5%AE%B6%E5%86%9B%E6%88%90%E5%88%86%E6%9F%A5%E8%AF%A2helper)时
如果使用自动显示模式，用户名后面的成分标识会重复产生，稳定复现
例图 [【水濑祈】明日方舟印象曲Crystallize live ver.](https://www.bilibili.com/video/BV1Df4y1u76W) 的评论区：
![image](https://github.com/user-attachments/assets/d75e327e-9298-4fac-80b6-967e1c4fa6b5)

手动模式下也会出现两个放大镜按钮，第一个能点击正常使用，第二个点击后无效
比如这则[巴别塔攻略组的动态](https://t.bilibili.com/868988196024746018)下的评论区：
![image](https://github.com/user-attachments/assets/9b2457cb-8a88-446b-8fba-d8bbe2d6530b)

**Comment by hmjz100** [comment]
抱歉，这个 Bug 暂时没有修复的可能性，故先关闭此议题
