### ISSUE TITLE
查询图标消失

### ISSUE THREAD

**Issue by redpepperpepper** [hmjz100/bilibili-comment-checker#23]
![QQ20240922-181815](https://github.com/user-attachments/assets/0c779db0-d145-4c40-a4b3-d9d32001bbf8)

**Comment by zhishixiang** [comment]
因为获取主页次数过多被风控了，只能进主页手动查

**Comment by CHENPrime-coder** [comment]
我也遇到了这个问题，不过不是风控。
我使用的是Edge浏览器，查了浏览器发现了如下原因：由于我的浏览器开启了夜间模式，然后源码里有这么一段：
![1](https://github.com/user-attachments/assets/b6ec8051-a9fb-4ed9-912b-39c776a8ec53)
我把红框部分注释掉就恢复了。
 这段代码是不是在浏览器夜间模式的情况下修改图标的颜色？如果是的话我认为并**不需要这个功能**，b站web端貌似没有夜间适配。
夜间模式的话完全可以用Dark Reader这种插件实现。

**Comment by hmjz100** [comment]
> 我也遇到了这个问题，不过不是风控。 我使用的是Edge浏览器，查了浏览器发现了如下原因：由于我的浏览器开启了夜间模式，然后源码里有这么一段： ![1](https://private-user-images.dgithub.xyz/79823878/374516256-b6ec8051-a9fb-4ed9-912b-39c776a8ec53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODY2NTgsIm5iZiI6MTcyODM4NjM1OCwicGF0aCI6Ii83OTgyMzg3OC8zNzQ1MTYyNTYtYjZlYzgwNTEtYTlmYi00ZWQ5LTkxMmItMzljNzc2YThlYzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDExMTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ODU0NjNhZGZjOWE3YTI1MjM0MDcxODJiYjA4ZmVmZWFjOWVkMTg5ZmJhZjc3ZjcyNDMwMWJlOThhOTA1YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EmFU0UrgJxKlRe2pvN_hL5flYpZQYPcsNtT-_Be4T7I) 我把红框部分注释掉就恢复了。 这段代码是不是在浏览器夜间模式的情况下修改图标的颜色？如果是的话我认为并**不需要这个功能**，b站web端貌似没有夜间适配。 夜间模式的话完全可以用Dark Reader这种插件实现。

这段代码是 #20 加入的，两边都要支持，我暂时没什么办法欸

**Comment by xinyihl** [comment]
可以参考一下其他[插件](https://github.com/magicdawn/bilibili-app-recommend/blob/4481e450fabfaf39feff47ba64736895bb36459d/src/modules/dark-mode/index.ts)的处理方法

**Comment by hmjz100** [comment]
这个方法在旧版页面是可以，但是新版B站页面有shadowRoot……

**Comment by hmjz100** [comment]
v2.0.7 已修改为紫色按钮~ 已经不需要夜晚模式啦~
