### ISSUE TITLE
世界弹射物语被识别为崩坏星穹铁道

### ISSUE THREAD

**Issue by Tekashi-gif** [hmjz100/bilibili-comment-checker#30]
man 我知道弹射现在很凉，但是被识别为崩铁真的有点....😭😭😭
![Image_1731298306645](https://github.com/user-attachments/assets/b1e684be-e282-4e66-baf1-4c8d1a954bfc)

**Comment by hmjz100** [comment]
嗯，下个版本会删除此关键词

**Comment by hmjz100** [comment]
v3.0 已删除该关键词~
