### ISSUE TITLE
【功能建议】把关键字的数据从代码剥离出来用Github、gitee存储，这样更新关键词就不用更新插件了

### ISSUE THREAD

**Issue by ZhianLin** [hmjz100/bilibili-comment-checker#32]
先从浏览器本地存储中读取checkers 的数据，本地没有数据或者数据是6个月前的再去Github读取，Github读取失败或者超时后再去gitee读取数据。

**Comment by hmjz100** [comment]
目前还没有把成分数据单独出来的想法，后续有想法了的话我应该会弄。
