### ISSUE TITLE
我没玩过碧蓝航线啊

### ISSUE THREAD

**Issue by tyy39** [hmjz100/bilibili-comment-checker#4]
![Snipaste_2024-08-29_20-19-40](https://github.com/user-attachments/assets/e6c6756b-811b-4d9c-8db5-cbf956578426)

**Comment by tyy39** [comment]
天地良心啊，碧蓝航线我都没下载过

**Comment by hmjz100** [comment]
知道知道，这是脚本的一个Bug，但是经过测试，如果把`动态页面内容检测`改为`仅读取发布动态文本`的话，就会导致很多已测出用户都变为无，最后反变成只有关注列表有效了，对于这个Bug一直没找到好的解决方法  
这样吧，下个版本就改为仅读取动态文本，但是不保证每个用户都有那么多花花绿绿的标签了

**Comment by hmjz100** [comment]
v2.0.0 已修改，应该不会误报了~
